
package mini_proyecto;
import java.awt.event.KeyEvent;
 import java.lang.String;
 import javax.swing.*;
public class ventana_principal extends javax.swing.JFrame {

 static POO objeto = new POO();
    public ventana_principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bienvenida = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Basica = new javax.swing.JRadioButton();
        Superior = new javax.swing.JRadioButton();
        Maestria = new javax.swing.JRadioButton();
        Comida = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Secundaria = new javax.swing.JRadioButton();
        Rock = new javax.swing.JCheckBox();
        Salsa = new javax.swing.JCheckBox();
        Pop = new javax.swing.JCheckBox();
        Reggaeton = new javax.swing.JCheckBox();
        Gaita = new javax.swing.JCheckBox();
        Joropo = new javax.swing.JCheckBox();
        edad = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        apellido = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        enviar = new javax.swing.JButton();
        limpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        datos = new javax.swing.JTextArea();
        Edad = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Apellido = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(-4144960,true));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bienvenida.setFont(new java.awt.Font("Monospaced", 1, 24));
        Bienvenida.setForeground(new java.awt.Color(-1,true));
        Bienvenida.setText("¡Bienvenido usuario!, registra tus datos aquí.");
        getContentPane().add(Bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 770, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(-1,true));
        jLabel2.setText("           Gustos musicales");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 170, -1));

        jLabel4.setFont(new java.awt.Font("DialogInput", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(-1,true));
        jLabel4.setText("Nivel de estudios");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 150, 20));

        Basica.setText("Basica");
        getContentPane().add(Basica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 100, -1));

        Superior.setText("Superior");
        Superior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuperiorActionPerformed(evt);
            }
        });
        getContentPane().add(Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 80, -1));

        Maestria.setText("Maestría");
        Maestria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaestriaActionPerformed(evt);
            }
        });
        getContentPane().add(Maestria, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 80, -1));

        Comida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Spaghetti", "Pabellón", "Mandocas", "Choripan" }));
        Comida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ComidaMouseClicked(evt);
            }
        });
        getContentPane().add(Comida, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 160, -1));

        jLabel3.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(-1,true));
        jLabel3.setText("Comida favorita");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 190, 20));

        Secundaria.setText("Secundaria");
        getContentPane().add(Secundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 100, -1));

        Rock.setText("Rock");
        getContentPane().add(Rock, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 293, 80, 20));

        Salsa.setBackground(new java.awt.Color(-1,true));
        Salsa.setText("Salsa");
        Salsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalsaActionPerformed(evt);
            }
        });
        getContentPane().add(Salsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 80, -1));

        Pop.setText("Pop");
        getContentPane().add(Pop, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 80, -1));

        Reggaeton.setText("Reggaeton");
        getContentPane().add(Reggaeton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        Gaita.setText("Gaita");
        getContentPane().add(Gaita, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 80, -1));

        Joropo.setText("Joropo");
        getContentPane().add(Joropo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 80, -1));

        edad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edad_limitador(evt);
            }
        });
        getContentPane().add(edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 200, 33));

        nombre.setToolTipText("No se puede agregar mas de 8 caracteres.");
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombre_limitador(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 200, 33));

        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                apellido_limitador(evt);
            }
        });
        getContentPane().add(apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 200, 33));

        direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                direccion_limitador(evt);
            }
        });
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 200, 33));

        enviar.setText("Enviar");
        enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutar_resultado(evt);
            }
        });
        getContentPane().add(enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 450, 120, 40));

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiar_datos(evt);
            }
        });
        getContentPane().add(limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 120, 40));

        datos.setColumns(20);
        datos.setRows(5);
        jScrollPane2.setViewportView(datos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 360, 123));

        Edad.setForeground(new java.awt.Color(-1,true));
        Edad.setText("       Edad");
        getContentPane().add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 79, -1));

        Nombre.setForeground(new java.awt.Color(-1,true));
        Nombre.setText("      Nombre");
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 80, -1));

        Apellido.setForeground(new java.awt.Color(-1,true));
        Apellido.setText("     Apellido");
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 62, -1));

        Direccion.setForeground(new java.awt.Color(-1,true));
        Direccion.setText("     Dirección");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 78, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/When.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 510));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 900, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void ejecutar_resultado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutar_resultado

// Declaración de variables contenedoras
String var2;    // Nombre
String var3;    // Apellido
String var4;    // Direccion
     
// Recolección de valores
String cnt_var1 = edad.getText();      // Variable contenedora
int var1 = Integer.parseInt(cnt_var1); // Transformación de String a int
// ---
var2= nombre.getText();
var3= apellido.getText();         
var4= direccion.getText();

/*
=====================
Inicio de debugger
=====================
Este algoritmo ejecutara varios procesos para verificar dos requisitos, la edad y longitud del nombre.
Una vez indetificado el caso de ambos, tomara las medidas adecuadas
*/

// Verificación de la longitud del nombre
if(nombre.getText().length()>8){
    getToolkit().beep();
    objeto.mensaje("No se puede insertar un nombre de mas de 8 caracteres");
    nombre.setText("");
    datos.setText("ERROR DE SINTAXIS");
   } 

// Verifacacion de la edad
if(var1 < 18) {
    getToolkit().beep();
    objeto.mensaje("Los menores de 18 años no pueden registrarse");
    edad.setText("");
    datos.setText("ERROR DE SINTAXIS");
} else if(var1 > 60) {
    getToolkit().beep();
    objeto.mensaje("Los mayores a 60 años no pueden registrarse");
    edad.setText("");
    datos.setText("ERROR DE SINTAXIS");
}

/*
=====================
Fin de debugger
=====================
*/

datos.setText(var1 + "\r\n" + var2 + "\r\n" + var3 + "\r\n" + var4);
}//GEN-LAST:event_ejecutar_resultado

private void nombre_limitador(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombre_limitador
char c = evt.getKeyChar();
if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_SPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_PERIOD) || (c==KeyEvent.VK_BACK_SPACE)  )) {
    objeto.mensaje("No puedes ingresar numeros en este campo");
    getToolkit().beep(); 
    evt.consume();
   }
}//GEN-LAST:event_nombre_limitador

private void edad_limitador(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edad_limitador
char c = evt.getKeyChar();
if(!(Character.isDigit(c) || (c==KeyEvent.VK_SPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_BACK_SPACE)  )) {
    objeto.mensaje("No puedes ingresar letras en este campo");
    getToolkit().beep(); 
    evt.consume(); 
   }
}//GEN-LAST:event_edad_limitador

    private void apellido_limitador(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellido_limitador
char c = evt.getKeyChar();
if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_SPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_PERIOD) || (c==KeyEvent.VK_BACK_SPACE)  )) {
    objeto.mensaje("No puedes ingresar numeros en este campo");
    getToolkit().beep(); 
    evt.consume();
}
    }//GEN-LAST:event_apellido_limitador

    private void direccion_limitador(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_direccion_limitador
char c = evt.getKeyChar();
if(!(Character.isAlphabetic(c) || (c==KeyEvent.VK_SPACE) || (c==KeyEvent.VK_DELETE) || (c==KeyEvent.VK_PERIOD) || (c==KeyEvent.VK_BACK_SPACE)  )) {
    objeto.mensaje("No puedes ingresar numeros en este campo");
    getToolkit().beep(); 
    evt.consume();
}
    }//GEN-LAST:event_direccion_limitador

private void limpiar_datos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiar_datos

// Pondra todos los campos de texto vacios  
edad.setText("");
nombre.setText("");
apellido.setText("");
direccion.setText("");
datos.setText("");

// Mensaje de tarea completada
getToolkit().beep(); 
objeto.mensaje("Limpieza exitosa");
}//GEN-LAST:event_limpiar_datos

private void SalsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalsaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_SalsaActionPerformed

private void ComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ComidaMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_ComidaMouseClicked

private void SuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuperiorActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_SuperiorActionPerformed

private void MaestriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaestriaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_MaestriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ventana_principal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellido;
    private javax.swing.JRadioButton Basica;
    private javax.swing.JLabel Bienvenida;
    private javax.swing.JComboBox Comida;
    private javax.swing.JLabel Direccion;
    private javax.swing.JLabel Edad;
    private javax.swing.JCheckBox Gaita;
    private javax.swing.JCheckBox Joropo;
    private javax.swing.JRadioButton Maestria;
    private javax.swing.JLabel Nombre;
    private javax.swing.JCheckBox Pop;
    private javax.swing.JCheckBox Reggaeton;
    private javax.swing.JCheckBox Rock;
    private javax.swing.JCheckBox Salsa;
    private javax.swing.JRadioButton Secundaria;
    private javax.swing.JRadioButton Superior;
    private javax.swing.JTextField apellido;
    private javax.swing.JTextArea datos;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField edad;
    private javax.swing.JButton enviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpiar;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
